from typing import Any
from uuid import NAMESPACE_URL, uuid5

import weaviate
from weaviate.classes.config import Configure, DataType, Property
from weaviate.classes.query import Filter, MetadataQuery

from app.config import settings


class WeaviateService:
    """
    Service responsible for storing and searching library pages
    in Weaviate.

    Embeddings are generated externally by EmbeddingService.
    """

    COLLECTION_NAME = "LibraryPage"

    def __init__(self, client: weaviate.WeaviateClient):
        self.client = client

    # ---------------------------------------------------------
    # Collection
    # ---------------------------------------------------------
    def create_collection(self) -> None:
        """
        Create the LibraryPage collection if it does not exist.
        Vectors are generated by EmbeddingService, so Weaviate
        uses self-provided vectors.
        """
        if self.client.collections.exists(self.COLLECTION_NAME):
            return

        self.client.collections.create(
            name=self.COLLECTION_NAME,
            vector_config=Configure.Vectors.self_provided(),
            properties=[
                Property(name="page_id", data_type=DataType.INT),
                Property(name="book_id", data_type=DataType.INT),
                Property(name="section_id", data_type=DataType.INT),
                Property(name="page_num", data_type=DataType.INT),
                Property(name="content", data_type=DataType.TEXT),
                Property(name="title", data_type=DataType.TEXT),
                Property(name="author", data_type=DataType.TEXT),
                Property(name="publisher", data_type=DataType.TEXT),
                Property(name="language", data_type=DataType.TEXT),
            ],
        )
        print(f"Collection '{self.COLLECTION_NAME}' created.")

    def delete_collection(self) -> None:
        """
        Delete the entire LibraryPage collection.

        WARNING: This deletes all indexed pages.
        Use only during development/testing.
        """
        if self.client.collections.exists(self.COLLECTION_NAME):
            self.client.collections.delete(self.COLLECTION_NAME)
            print(f"Collection '{self.COLLECTION_NAME}' deleted.")

    # ---------------------------------------------------------
    # Insert
    # ---------------------------------------------------------
    def insert(
        self,
        page: dict[str, Any],
        vector: list[float],
    ) -> str:
        """
        Insert or replace one library page.

        The UUID is deterministic based on page_id,
        so ingesting the same page multiple times
        does not create duplicate objects.
        """
        collection = self.client.collections.get(self.COLLECTION_NAME)

        page_id = page["page_id"]
        object_uuid = uuid5(
            NAMESPACE_URL,
            f"library-page-{page_id}",
        )

        properties = {
            "page_id": page["page_id"],
            "book_id": page["book_id"],
            "section_id": page.get("section_id"),
            "page_num": page.get("page_num"),
            "content": page["content"],
            "title": page.get("title"),
            "author": page.get("author"),
            "publisher": page.get("publisher"),
            "language": page.get("language"),
        }

        collection.data.insert(
            uuid=object_uuid,
            properties=properties,
            vector=vector,
        )

        return str(object_uuid)

    def insert_batch(
        self,
        pages: list[dict[str, Any]],
        vectors: list[list[float]],
    ) -> None:
        """
        Insert multiple library pages into Weaviate.

        Each page receives a deterministic UUID based on page_id.
        This makes ingestion idempotent: running the same ingestion
        multiple times will not create duplicate pages.
        """
        if len(pages) != len(vectors):
            raise ValueError(
                "Number of pages must match "
                "number of vectors."
            )

        collection = self.client.collections.get(
            self.COLLECTION_NAME
        )

        with collection.batch.dynamic() as batch:

            for page, vector in zip(
                pages,
                vectors,
            ):

                page_id = page["page_id"]

                object_uuid = uuid5(
                    NAMESPACE_URL,
                    f"library-page-{page_id}",
                )

                properties = {
                    "page_id": page["page_id"],
                    "book_id": page["book_id"],
                    "section_id": page.get("section_id"),
                    "page_num": page.get("page_num"),
                    "content": page["content"],
                    "title": page.get("title"),
                    "author": page.get("author"),
                    "publisher": page.get("publisher"),
                    "language": page.get("language"),
                }

                batch.add_object(
                    uuid=object_uuid,
                    properties=properties,
                    vector=vector,
                )

    # ---------------------------------------------------------
    # Search
    # ---------------------------------------------------------
    def search(
        self,
        vector: list[float],
        limit: int = 5,
    ) -> list[dict[str, Any]]:
        """Search library pages using vector similarity."""
        collection = self.client.collections.get(self.COLLECTION_NAME)

        response = collection.query.near_vector(
            near_vector=vector,
            limit=limit,
            return_metadata=MetadataQuery(distance=True),
        )

        results = []
        for obj in response.objects:
            results.append(
                {
                    "id": str(obj.uuid),
                    "distance": obj.metadata.distance,
                    "page_id": obj.properties.get("page_id"),
                    "book_id": obj.properties.get("book_id"),
                    "section_id": obj.properties.get("section_id"),
                    "page_num": obj.properties.get("page_num"),
                    "content": obj.properties.get("content"),
                    "title": obj.properties.get("title"),
                    "author": obj.properties.get("author"),
                    "publisher": obj.properties.get("publisher"),
                    "language": obj.properties.get("language"),
                }
            )

        return results

    def keyword_search(
        self,
        query: str,
        limit: int = 5,
    ) -> list[dict[str, Any]]:
        """Perform BM25 keyword search."""
        collection = self.client.collections.get(self.COLLECTION_NAME)

        response = collection.query.bm25(
            query=query,
            limit=limit,
        )

        results = []
        for obj in response.objects:
            results.append(
                {
                    "id": str(obj.uuid),
                    "page_id": obj.properties.get("page_id"),
                    "book_id": obj.properties.get("book_id"),
                    "section_id": obj.properties.get("section_id"),
                    "page_num": obj.properties.get("page_num"),
                    "content": obj.properties.get("content"),
                    "title": obj.properties.get("title"),
                    "author": obj.properties.get("author"),
                    "publisher": obj.properties.get("publisher"),
                    "language": obj.properties.get("language"),
                }
            )

        return results

    def hybrid_search(
        self,
        query: str,
        vector: list[float],
        limit: int,
    ) -> list[dict]:
        """
        Perform hybrid retrieval.

        Dense/vector weight: 0.4
        BM25 weight: 0.6

        Weaviate alpha:
            1.0 = purely vector
            0.0 = purely BM25

        Therefore:
            alpha = 0.4
        """
        collection = self.client.collections.get(
            self.COLLECTION_NAME
        )

        response = collection.query.hybrid(
            query=query,
            vector=vector,
            alpha=settings.retrieval_dense_weight,
            limit=limit,
            return_metadata=MetadataQuery(
                score=True,
                explain_score=True,
            ),
        )

        results = []

        for obj in response.objects:

            result = {
                "uuid": str(obj.uuid),
                "score": obj.metadata.score,
                "explain_score": obj.metadata.explain_score,
                **obj.properties,
            }

            results.append(result)

        return results

    def get_by_page_id(
        self,
        page_id: int,
    ) -> dict | None:
        """
        Retrieve a single library page by its page_id.
        Uses a filter query since page_id is stored as a property.
        """
        collection = self.client.collections.get(self.COLLECTION_NAME)

        response = collection.query.fetch_objects(
            filters=Filter.by_property("page_id").equal(page_id),
            limit=1,
        )

        if not response.objects:
            return None

        obj = response.objects[0]

        return {
            "uuid": str(obj.uuid),
            "page_id": obj.properties.get("page_id"),
            "book_id": obj.properties.get("book_id"),
            "section_id": obj.properties.get("section_id"),
            "page_num": obj.properties.get("page_num"),
            "content": obj.properties.get("content"),
            "title": obj.properties.get("title"),
            "author": obj.properties.get("author"),
            "publisher": obj.properties.get("publisher"),
            "language": obj.properties.get("language"),
        }

    # ---------------------------------------------------------
    # Delete
    # ---------------------------------------------------------
    def delete(self, object_id: str) -> None:
        """Delete a library page from Weaviate by UUID."""
        collection = self.client.collections.get(self.COLLECTION_NAME)
        collection.data.delete_by_id(object_id)

    def delete_by_page_id(
        self,
        page_id: int,
    ) -> bool:
        """
        Delete a library page by its page_id.
        Reconstructs the deterministic UUID and deletes it.
        Returns True if deleted, False if not found.
        """
        page = self.get_by_page_id(page_id)
        if page is None:
            return False

        object_uuid = uuid5(
            NAMESPACE_URL,
            f"library-page-{page_id}",
        )

        collection = self.client.collections.get(self.COLLECTION_NAME)
        collection.data.delete_by_id(str(object_uuid))

        return True